version: '3.8'

services:
    app:
        user: "1000"
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVER_NAME: taskhandler.local
        container_name: laravel_app
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html   # monter toute la racine du projet
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: laravel
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:


